import { defineField, defineType } from 'sanity';

export const homeContent = defineType({
  name: 'homeContent',
  title: 'Home Page Content',
  type: 'document',
  fieldsets: [
    {
      name: 'heroSettings',
      title: 'Hero Settings',
      description: 'Hero headline, copy, imagery, and CTA actions.',
    },
    {
      name: 'statsBar',
      title: 'Stats Bar',
      description: 'Visibility and metrics shown in the stats bar.',
    },
    {
      name: 'aboutSection',
      title: 'About Preview Section',
      description: 'Visibility, copy, links, and imagery for the about preview.',
    },
    {
      name: 'programsSection',
      title: 'Programs Grid Section',
      description: 'Visibility and labels for the programs section.',
    },
    {
      name: 'transparencySection',
      title: 'Transparency Section',
      description: 'Donor accountability progress bars and badges.',
    },
    {
      name: 'testimonialsSection',
      title: 'Testimonials / Stories',
      description: 'Real voices and impact testimonials.',
    },
    {
      name: 'visionMissionSection',
      title: 'Vision & Mission',
      description: 'Vision/Mission copy and icon selections.',
    },
    {
      name: 'quoteBannerSection',
      title: 'Quote Banner',
      description: 'Italic quotes, background imagery, and titles.',
    },
    {
      name: 'ctaSection',
      title: 'Call To Action',
      description: 'CTA headline, copy, and buttons.',
    },
  ],
  fields: [
    // Hero Settings
    defineField({
      name: 'showHeroSection',
      title: 'Show Hero Section?',
      type: 'boolean',
      initialValue: true,
      fieldset: 'heroSettings',
    }),
    defineField({
      name: 'heroEyebrow',
      title: 'Hero Eyebrow Label',
      type: 'string',
      initialValue: 'Registered Charitable Trust',
      fieldset: 'heroSettings',
    }),
    defineField({
      name: 'heroTitle',
      title: 'Hero Title',
      type: 'string',
      initialValue: 'Empowering Communities Through Knowledge & Care',
      validation: (Rule) => Rule.required(),
      fieldset: 'heroSettings',
    }),
    defineField({
      name: 'heroSubtitle',
      title: 'Hero Subtitle',
      type: 'string',
      initialValue: 'Dedicated to holistic social welfare, learning excellence, and healthcare access.',
      validation: (Rule) => Rule.required(),
      fieldset: 'heroSettings',
    }),
    defineField({
      name: 'heroDescription',
      title: 'Hero Description',
      type: 'text',
      initialValue: 'IKC Foundation is a registered charitable trust creating sustainable, grassroots changes in education, healthcare, environment, and rural livelihood support.',
      validation: (Rule) => Rule.required(),
      fieldset: 'heroSettings',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Background Image',
      type: 'image',
      options: { hotspot: true },
      fieldset: 'heroSettings',
    }),
    defineField({
      name: 'heroImageAlt',
      title: 'Hero Image Alt Text',
      type: 'string',
      initialValue: 'Aerial view of community village project',
      fieldset: 'heroSettings',
    }),
    defineField({
      name: 'heroPrimaryCtaLabel',
      title: 'Hero Primary CTA Label',
      type: 'string',
      initialValue: 'Our Mission',
      validation: (Rule) => Rule.required(),
      fieldset: 'heroSettings',
    }),
    defineField({
      name: 'heroPrimaryCtaLink',
      title: 'Hero Primary CTA Link',
      type: 'string',
      initialValue: '/about',
      validation: (Rule) => Rule.required(),
      fieldset: 'heroSettings',
    }),
    defineField({
      name: 'heroSecondaryCtaLabel',
      title: 'Hero Secondary CTA Label',
      type: 'string',
      initialValue: 'Support Us',
      validation: (Rule) => Rule.required(),
      fieldset: 'heroSettings',
    }),
    defineField({
      name: 'heroSecondaryCtaLink',
      title: 'Hero Secondary CTA Link',
      type: 'string',
      initialValue: '/contact',
      validation: (Rule) => Rule.required(),
      fieldset: 'heroSettings',
    }),

    // Stats Section
    defineField({
      name: 'showStatsSection',
      title: 'Show Stats Section?',
      type: 'boolean',
      initialValue: true,
      fieldset: 'statsBar',
    }),
    defineField({
      name: 'stats',
      title: 'Stats Counters',
      type: 'array',
      of: [
        {
          type: 'object',
          name: 'homeStat',
          title: 'Home Stat',
          fields: [
            { name: 'number', title: 'Number / Percentage', type: 'string', validation: (Rule) => Rule.required() },
            { name: 'label', title: 'Metric Label', type: 'string', validation: (Rule) => Rule.required() },
          ],
        },
      ],
      initialValue: [
        { number: '12,000+', label: 'Lives Impacted' },
        { number: '40+', label: 'Rural Villages Served' },
        { number: '250+', label: 'Active Volunteers' },
        { number: '85%', label: 'Direct Fund Allocation' },
      ],
      fieldset: 'statsBar',
    }),

    // About Preview Section
    defineField({
      name: 'showAboutSection',
      title: 'Show About Preview Section?',
      type: 'boolean',
      initialValue: true,
      fieldset: 'aboutSection',
    }),
    defineField({
      name: 'aboutEyebrow',
      title: 'About Eyebrow',
      type: 'string',
      initialValue: 'Who We Are',
      fieldset: 'aboutSection',
    }),
    defineField({
      name: 'aboutTitle',
      title: 'About Section Title',
      type: 'string',
      initialValue: 'Uniting Care and Knowledge to Build Sustainable Livelihoods',
      fieldset: 'aboutSection',
    }),
    defineField({
      name: 'aboutImage',
      title: 'About Preview Image',
      type: 'image',
      options: { hotspot: true },
      fieldset: 'aboutSection',
    }),
    defineField({
      name: 'aboutImageAlt',
      title: 'About Image Alt Text',
      type: 'string',
      initialValue: 'Community learning initiative',
      fieldset: 'aboutSection',
    }),
    defineField({
      name: 'aboutInceptionYear',
      title: 'Inception Year Tag',
      type: 'string',
      initialValue: '2005',
      fieldset: 'aboutSection',
    }),
    defineField({
      name: 'aboutInceptionLabel',
      title: 'Inception Label Tag',
      type: 'string',
      initialValue: 'Inception Year',
      fieldset: 'aboutSection',
    }),
    defineField({
      name: 'aboutLinkLabel',
      title: 'About Section Link Label',
      type: 'string',
      initialValue: 'Read Our Full Story',
      fieldset: 'aboutSection',
    }),
    defineField({
      name: 'aboutLinkHref',
      title: 'About Section Link URL',
      type: 'string',
      initialValue: '/about',
      fieldset: 'aboutSection',
    }),

    // Programs Section
    defineField({
      name: 'showProgramsSection',
      title: 'Show Programs Section?',
      type: 'boolean',
      initialValue: true,
      fieldset: 'programsSection',
    }),
    defineField({
      name: 'programsEyebrow',
      title: 'Programs Section Eyebrow',
      type: 'string',
      initialValue: 'Our Programs',
      fieldset: 'programsSection',
    }),
    defineField({
      name: 'programsIntroTitle',
      title: 'Programs Section Intro Title',
      type: 'string',
      initialValue: 'Core Fields of Active Engagement',
      fieldset: 'programsSection',
    }),
    defineField({
      name: 'programsIntroDescription',
      title: 'Programs Section Intro Description',
      type: 'text',
      initialValue: 'Direct grassroots interventions seeking to address basic life needs, educational growth, and ecological balance.',
      fieldset: 'programsSection',
    }),
    defineField({
      name: 'programsCardLabel',
      title: 'Programs Card Bottom Label',
      type: 'string',
      initialValue: 'Active Program',
      fieldset: 'programsSection',
    }),
    defineField({
      name: 'programsCardLinkAriaLabel',
      title: 'Programs Card Arrow Link ARIA Label',
      type: 'string',
      initialValue: 'View program details',
      fieldset: 'programsSection',
    }),
    defineField({
      name: 'programsLinkHref',
      title: 'Programs Section Fallback Link URL',
      type: 'string',
      initialValue: '/programs',
      fieldset: 'programsSection',
    }),

    // Transparency Section
    defineField({
      name: 'showTransparencySection',
      title: 'Show Transparency Section?',
      type: 'boolean',
      initialValue: true,
      fieldset: 'transparencySection',
    }),
    defineField({
      name: 'transparencyEyebrow',
      title: 'Transparency Section Eyebrow',
      type: 'string',
      initialValue: 'Transparency',
      fieldset: 'transparencySection',
    }),
    defineField({
      name: 'transparencyTitle',
      title: 'Transparency Section Title',
      type: 'string',
      initialValue: '85% of Funds Go Directly to Program Execution',
      fieldset: 'transparencySection',
    }),
    defineField({
      name: 'transparencyDescription',
      title: 'Transparency Section Description',
      type: 'text',
      initialValue: 'We maintain strict accountability. Administrative and fundraising costs are kept to a bare minimum (15% combined) to ensure that donations directly support grassroots execution in villages and slums.',
      fieldset: 'transparencySection',
    }),
    defineField({
      name: 'transparencyBars',
      title: 'Transparency Progress Bars',
      type: 'array',
      of: [
        {
          type: 'object',
          name: 'transparencyBar',
          title: 'Transparency Metric',
          fields: [
            { name: 'label', title: 'Metric Label', type: 'string', validation: (Rule) => Rule.required() },
            { name: 'value', title: 'Display Value (e.g. 85%)', type: 'string', validation: (Rule) => Rule.required() },
            { name: 'width', title: 'Bar Percentage (0 - 100)', type: 'number', validation: (Rule) => Rule.min(0).max(100).required() },
            {
              name: 'color',
              title: 'Color Option',
              type: 'string',
              options: {
                list: [
                  { title: 'Teal (Primary Theme)', value: 'bg-teal-600' },
                  { title: 'Slate Grey', value: 'bg-slate-400' },
                  { title: 'Light Grey', value: 'bg-slate-300' },
                  { title: 'Amber / Yellow Accent', value: 'bg-amber-500' },
                ],
              },
              initialValue: 'bg-teal-600',
            },
          ],
        },
      ],
      initialValue: [
        { label: 'Direct Program Execution', value: '85%', width: 85, color: 'bg-teal-600' },
        { label: 'Administrative Management & Support', value: '10%', width: 10, color: 'bg-slate-400' },
        { label: 'Development & Fundraising', value: '5%', width: 5, color: 'bg-slate-300' },
      ],
      fieldset: 'transparencySection',
    }),
    defineField({
      name: 'transparencyBadges',
      title: 'Transparency Badges List',
      type: 'array',
      of: [
        {
          type: 'object',
          name: 'transparencyBadge',
          title: 'Badge Card',
          fields: [
            { name: 'title', title: 'Badge Title', type: 'string', validation: (Rule) => Rule.required() },
            { name: 'description', title: 'Badge Description', type: 'text', validation: (Rule) => Rule.required() },
          ],
        },
      ],
      initialValue: [
        { title: 'Tax Exemptions', description: 'Donations qualify for valid 80G tax exemptions under Indian Trust Registration acts.' },
        { title: 'Minimal Overhead', description: 'Strict audit standards ensure funds are utilized with maximal efficiency.' },
        { title: 'Annual Reports', description: 'Verified balance sheets, annual project reviews, and medical camp summaries are published transparently for public auditing.' },
      ],
      fieldset: 'transparencySection',
    }),

    // Testimonials
    defineField({
      name: 'showTestimonialsSection',
      title: 'Show Testimonials Section?',
      type: 'boolean',
      initialValue: true,
      fieldset: 'testimonialsSection',
    }),
    defineField({
      name: 'testimonialsEyebrow',
      title: 'Testimonials Section Eyebrow',
      type: 'string',
      initialValue: 'Our Impact',
      fieldset: 'testimonialsSection',
    }),
    defineField({
      name: 'testimonialsTitle',
      title: 'Testimonials Section Title',
      type: 'string',
      initialValue: 'Stories of Direct Hope',
      fieldset: 'testimonialsSection',
    }),
    defineField({
      name: 'testimonialsDescription',
      title: 'Testimonials Section Description',
      type: 'text',
      initialValue: 'Real voices from families, students, and elders whom IKC Foundation programs have had the privilege to serve.',
      fieldset: 'testimonialsSection',
    }),
    defineField({
      name: 'testimonials',
      title: 'Testimonial Quotes',
      type: 'array',
      of: [
        {
          type: 'object',
          name: 'testimonial',
          title: 'Testimonial',
          fields: [
            { name: 'quote', title: 'Quote Text', type: 'text', validation: (Rule) => Rule.required() },
            { name: 'author', title: 'Author Name', type: 'string', validation: (Rule) => Rule.required() },
            { name: 'role', title: 'Author Subtitle / Location', type: 'string', validation: (Rule) => Rule.required() },
          ],
        },
      ],
      initialValue: [
        { quote: 'The free health camp in our village diagnosed my mother\'s cardiac condition just in time. The medication support provided by IKC has been a blessing.', author: 'Ramesh Mondal', role: 'Farmer, Sundarbans Region' },
        { quote: 'Thanks to the IKC study fellowship, I can continue my college education without placing a financial burden on my father.', author: 'Priya Sharma', role: 'Science Undergraduate Student' },
      ],
      fieldset: 'testimonialsSection',
    }),

    // Vision & Mission Cards
    defineField({
      name: 'showVisionMissionSection',
      title: 'Show Vision & Mission Section?',
      type: 'boolean',
      initialValue: true,
      fieldset: 'visionMissionSection',
    }),
    defineField({
      name: 'visionMissionEyebrow',
      title: 'Vision & Mission Eyebrow',
      type: 'string',
      initialValue: 'Vision & Mission',
      fieldset: 'visionMissionSection',
    }),
    defineField({
      name: 'visionTitle',
      title: 'Vision Section Title',
      type: 'string',
      initialValue: 'Our Vision',
      validation: (Rule) => Rule.required(),
      fieldset: 'visionMissionSection',
    }),
    defineField({
      name: 'visionDescription',
      title: 'Vision Description',
      type: 'text',
      initialValue: 'To build an inclusive, knowledgeable, and healthy society where every individual has access to opportunities for a dignified and empowered life.',
      validation: (Rule) => Rule.required(),
      fieldset: 'visionMissionSection',
    }),
    defineField({
      name: 'visionIcon',
      title: 'Vision Icon',
      type: 'string',
      initialValue: 'Target',
      options: {
        list: [
          { title: 'Target', value: 'Target' },
          { title: 'Sparkles', value: 'Sparkles' },
          { title: 'Heart', value: 'Heart' },
          { title: 'Users', value: 'Users' },
          { title: 'Leaf', value: 'Leaf' },
          { title: 'Award', value: 'Award' },
          { title: 'GraduationCap', value: 'GraduationCap' },
          { title: 'Ambulance', value: 'Ambulance' },
          { title: 'AlertTriangle', value: 'AlertTriangle' },
          { title: 'Handshake', value: 'Handshake' },
        ],
      },
      fieldset: 'visionMissionSection',
    }),
    defineField({
      name: 'missionTitle',
      title: 'Mission Section Title',
      type: 'string',
      initialValue: 'Our Mission',
      validation: (Rule) => Rule.required(),
      fieldset: 'visionMissionSection',
    }),
    defineField({
      name: 'missionDescription',
      title: 'Mission Description',
      type: 'text',
      initialValue: 'To drive direct, impactful social initiatives in rural and underprivileged communities through education, healthcare camps, and ecological conservation projects.',
      validation: (Rule) => Rule.required(),
      fieldset: 'visionMissionSection',
    }),
    defineField({
      name: 'missionIcon',
      title: 'Mission Icon',
      type: 'string',
      initialValue: 'Sparkles',
      options: {
        list: [
          { title: 'Sparkles', value: 'Sparkles' },
          { title: 'Target', value: 'Target' },
          { title: 'Heart', value: 'Heart' },
          { title: 'Users', value: 'Users' },
          { title: 'Leaf', value: 'Leaf' },
          { title: 'Award', value: 'Award' },
          { title: 'GraduationCap', value: 'GraduationCap' },
          { title: 'Ambulance', value: 'Ambulance' },
          { title: 'AlertTriangle', value: 'AlertTriangle' },
          { title: 'Handshake', value: 'Handshake' },
        ],
      },
      fieldset: 'visionMissionSection',
    }),

    // Quote Banner
    defineField({
      name: 'showQuoteBannerSection',
      title: 'Show Quote Banner Section?',
      type: 'boolean',
      initialValue: true,
      fieldset: 'quoteBannerSection',
    }),
    defineField({
      name: 'commitmentTitle',
      title: 'Commitment Section Title',
      type: 'string',
      initialValue: 'Our Commitment',
      validation: (Rule) => Rule.required(),
      fieldset: 'quoteBannerSection',
    }),
    defineField({
      name: 'commitmentDescription',
      title: 'Commitment Description',
      type: 'text',
      initialValue: 'We believe that real change begins with localized, transparent, and direct community care.',
      validation: (Rule) => Rule.required(),
      fieldset: 'quoteBannerSection',
    }),
    defineField({
      name: 'commitmentImage',
      title: 'Commitment Banner Background Image',
      type: 'image',
      options: { hotspot: true },
      fieldset: 'quoteBannerSection',
    }),
    defineField({
      name: 'commitmentImageAlt',
      title: 'Commitment Image Alt Text',
      type: 'string',
      initialValue: 'Rural outreach community support',
      fieldset: 'quoteBannerSection',
    }),

    // CTA Section
    defineField({
      name: 'showCtaSection',
      title: 'Show CTA Section?',
      type: 'boolean',
      initialValue: true,
      fieldset: 'ctaSection',
    }),
    defineField({
      name: 'ctaEyebrow',
      title: 'CTA Eyebrow Label',
      type: 'string',
      initialValue: 'Join Our Outreach',
      fieldset: 'ctaSection',
    }),
    defineField({
      name: 'ctaTitle',
      title: 'CTA Section Title',
      type: 'string',
      initialValue: 'Become Part of the Change Today',
      validation: (Rule) => Rule.required(),
      fieldset: 'ctaSection',
    }),
    defineField({
      name: 'ctaDescription',
      title: 'CTA Description',
      type: 'text',
      initialValue: 'Your involvement helps us expand our mobile health clinics, build learning classrooms, and protect regional ecology.',
      validation: (Rule) => Rule.required(),
      fieldset: 'ctaSection',
    }),
    defineField({
      name: 'ctaPrimaryLabel',
      title: 'CTA Primary Button Label',
      type: 'string',
      initialValue: 'Inquire & Volunteer',
      validation: (Rule) => Rule.required(),
      fieldset: 'ctaSection',
    }),
    defineField({
      name: 'ctaPrimaryLink',
      title: 'CTA Primary Button Link URL',
      type: 'string',
      initialValue: '/contact',
      validation: (Rule) => Rule.required(),
      fieldset: 'ctaSection',
    }),
    defineField({
      name: 'ctaSecondaryLabel',
      title: 'CTA Secondary Button Label',
      type: 'string',
      initialValue: 'Learn More About IKC',
      validation: (Rule) => Rule.required(),
      fieldset: 'ctaSection',
    }),
    defineField({
      name: 'ctaSecondaryLink',
      title: 'CTA Secondary Button Link URL',
      type: 'string',
      initialValue: '/about',
      validation: (Rule) => Rule.required(),
      fieldset: 'ctaSection',
    }),
  ],
  preview: {
    prepare() {
      return {
        title: 'Home Page Content (Singleton)',
      };
    },
  },
});
